Tag6 fixed
scverse/scvi-tools pull request #1501
Opened 2022-04-08 02:09 UTC by cane11

2022-04-08 02:28 UTC, adamgayoso requested changes

2022-04-08 02:28 UTC, adamgayoso commented on docs/user_guide/models/destvi.md
> +$\lambda_{\beta}$ (l1_reg in code), $\lambda_{\eta}$ (eta_reg in code) and $\lambda_{\alpha}$ (beta_reg in code) are hyperparameters used to scale the loss term. Increasing \lambda_{\beta} leads to i
```suggestion
$\lambda_{\beta}$ (`l1_reg` in code), $\lambda_{\eta}$ (`eta_reg` in code) and $\lambda_{\alpha}$ (`beta_reg` in code) are hyperparameters used to scale the loss term. Increasing $\lambda_{\beta}$ leads to increased sparsity of cell type proportions. Increasing $\lambda_{\alpha}$ leads to less model flexibility for technical variation between single cell and spatial sequencing dataset. Increasing $\lambda_{\eta}$ leads to more genes being explained by the noise factor (we recommend to keep this constant). 
```

2022-04-08 03:37 UTC, romain-lopez commented on docs/user_guide/models/destvi.md
> +     &+ \lambda_{\alpha} \mathrm{Var}(\alpha) - \log p(\gamma \mid \mathrm{VampPrior}) + \lambda_{\beta} \lVert \beta_{sc} \rVert_1  \tag{6} \\
Suggestion: 

> \mathrm{Var}(\alpha)
where $\mathrm{Var}(\alpha)$ refers to the empirical variance of the parameters alpha across all genes. We used this as a practical form of regularization (a similar regularizer is used in the ZINB-WaVE model).

2022-04-11 22:12 UTC, adamgayoso approved these changes

2022-04-11 22:39 UTC, merged