New fields: numerical var and varm
scverse/scvi-tools pull request #1810
Opened 2022-11-29 14:57 UTC by vitkl

These fields are needed when the dataset is split into batches of both cells and variables.

2022-12-02 19:20 UTC, martinkim0 commented on scvi/data/fields/_var_field.py
> +    Parameters
```suggestion
    An abstract AnnDataField for .var attributes in the AnnData data structure.
    
    Parameters
```

2022-12-02 19:21 UTC, martinkim0 commented on scvi/data/fields/_var_field.py
> +    Parameters
```suggestion
    An AnnDataField for numerical .var attributes in the AnnData data structure.
    
    Parameters
```

2022-12-02 19:21 UTC, martinkim0 commented on scvi/data/fields/_varm_field.py
> +    Parameters
```suggestion
    An AnnDataField for an .varm field in the AnnData data structure.
    
    In addition to creating a reference to the .varm field, stores the column
    keys for the varm field in a more accessible .uns attribute.
    
    Parameters
```

2022-12-02 19:22 UTC, martinkim0 commented on scvi/data/fields/_varm_field.py
> +        If the ``colnames_uns_key`` was specified, then the columns stored in that
```suggestion
        Returns a list or NumPy array of column names that will be used for the relevant .varm data.
        
        If the ``colnames_uns_key`` was specified, then the columns stored in that
```

2022-12-02 20:44 UTC, martinkim0 approved these changes
LGTM, ready to merge after precommit and Codacy issues are addressed!

2022-12-02 20:46 UTC, adamgayoso requested changes
Thanks! Would you be able to add the classes to our docs too?

2022-12-12 16:55 UTC, adamgayoso commented
Actually, thinking about this again, there's going to be a lot of copy/paste between the obs analogs. I think it makes sense to go deeper with the abstraction so we can reduce code duplication. We are on it from our side @vitkl

2022-12-12 18:00 UTC, martinkim0 commented
Closed in favor of #1821

2022-12-12 18:00 UTC, closed without merging