[WIP] autotune api
scverse/scvi-tools pull request #997
Opened 2021-03-09 11:42 UTC by mjayasur

2021-03-19 18:03 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +    ):
**kwargs to tune.run

2021-04-18 17:25 UTC, adamgayoso requested changes

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +        plan_hyperparams: dict = {},
Remove mutable defaults, should be `Optional[dict] = None`

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +    def _scvi_trainable(self, config, checkpoint_dir=None):
I'd call this just `_trainable` or something

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +        num_samples=10,
typing

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +    Hyperparameter tuning for SCVI using Ray Tune.
```suggestion
    Hyperparameter tuning using Ray Tune.
```

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +
document kwargs

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +        Run hyper parameter tuning experiment.
some description that this is a wrapper of tune.run

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +
also a returns part describing the outputs

2021-04-18 17:25 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +        scheduler,
should there be a default scheduler? So default is None and if None, use Asha...

2021-05-01 19:08 UTC, adamgayoso requested changes

2021-05-01 19:08 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +        name: str = "scvi-experiment",
let's add a default search alg (hyperopt) default None here

2021-05-07 17:29 UTC, adamgayoso commented on scvi/autotune/_wrappers.py
> +        "n_latent": choice([i for i in range(5, 15)]),
`batch_size: choice([128, 256, 512, 1024])`

2021-05-07 17:30 UTC, adamgayoso commented on scvi/autotune/_autotune.py
> +                resources_per_trial = {"cpu": 1, "gpu": 1}
let's see if we can run multiple trials on the same gpu

2021-05-07 17:43 UTC, mjayasur commented
mmd default and FIFO

2021-05-07 17:43 UTC, mjayasur commented
stochastic_weight_avg

2021-09-21 23:36 UTC, adamgayoso commented on scvi/autotune/_callbacks.py
> +    def __init__(
add documentation to this callback

2021-09-21 23:37 UTC, adamgayoso commented on scvi/autotune/_callbacks.py
> +        metric_functions=None,
add somewhere how metric functions need to be formatted

2021-09-21 23:38 UTC, adamgayoso commented on scvi/autotune/_metrics.py
> +    )
remove for now

2021-11-12 20:04 UTC, adamgayoso commented on scvi/autotune/_callbacks.py
> +        metric_functions=None,
also need to check that their signature is correct

2022-07-28 20:15 UTC, jjhong922 commented
Closed in favor of https://github.com/scverse/scvi-tools/pull/1565

2022-07-28 20:15 UTC, closed without merging